TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += pre4500.db
DATA += pre4500.proto

#=======================================
include $(TOP)/configure/RULES
